set lines 1000;
set pages 2000;
set scan off;
set serveroutput on;

spool 'CreateTablespaces.log'
-----------------------------------------------------------------------

CREATE TABLESPACE MSP_DATATS DATAFILE 
  'D:\software\eclipse\OracleXE112_Win32\oraclexe\app\oracle\oradata\XE\MSP_DATATS.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

CREATE TABLESPACE MSP_INDXTS DATAFILE 
  'D:\software\eclipse\OracleXE112_Win32\oraclexe\app\oracle\oradata\XE\MSP_INDXTS.DBF' SIZE 1000M AUTOEXTEND ON NEXT 100M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


CREATE PROFILE YUGMSP_PROFILE LIMIT
  SESSIONS_PER_USER UNLIMITED
  CPU_PER_SESSION DEFAULT
  CPU_PER_CALL DEFAULT
  CONNECT_TIME UNLIMITED
  IDLE_TIME DEFAULT
  LOGICAL_READS_PER_SESSION DEFAULT
  LOGICAL_READS_PER_CALL DEFAULT
  COMPOSITE_LIMIT DEFAULT
  PRIVATE_SGA DEFAULT
  FAILED_LOGIN_ATTEMPTS DEFAULT
  PASSWORD_LIFE_TIME UNLIMITED
  PASSWORD_REUSE_TIME 1
  PASSWORD_REUSE_MAX 12
  PASSWORD_LOCK_TIME DEFAULT
  PASSWORD_GRACE_TIME DEFAULT
  PASSWORD_VERIFY_FUNCTION DEFAULT;



CREATE USER YUG_MSP
  IDENTIFIED BY mdm_owner
  DEFAULT TABLESPACE MSP_DATATS
  TEMPORARY TABLESPACE TEMP
  PROFILE YUGMSP_PROFILE
  ACCOUNT UNLOCK;
  -- 7 Roles for YUG_MSP 
  GRANT CONNECT TO YUG_MSP;
  GRANT SELECT_CATALOG_ROLE TO YUG_MSP;
  GRANT EXECUTE_CATALOG_ROLE TO YUG_MSP;
  GRANT IMP_FULL_DATABASE TO YUG_MSP;
  GRANT HS_ADMIN_ROLE TO YUG_MSP;
  GRANT RESOURCE TO YUG_MSP;
  ALTER USER YUG_MSP DEFAULT ROLE ALL;
  -- 82 System Privileges for YUG_MSP 
  GRANT CREATE ANY SQL PROFILE TO YUG_MSP;
  GRANT DROP ANY SQL PROFILE TO YUG_MSP;
  GRANT DROP ANY CONTEXT TO YUG_MSP;
  GRANT CREATE ANY DIMENSION TO YUG_MSP;
  GRANT CREATE ANY MATERIALIZED VIEW TO YUG_MSP;
  GRANT CREATE ANY TRIGGER TO YUG_MSP;
  GRANT CREATE ROLE TO YUG_MSP;
  GRANT CREATE ANY VIEW TO YUG_MSP;
  GRANT DROP PUBLIC SYNONYM TO YUG_MSP;
  GRANT CREATE ANY SYNONYM TO YUG_MSP;
  GRANT CREATE CLUSTER TO YUG_MSP;
  GRANT INSERT ANY TABLE TO YUG_MSP;
  GRANT DROP ANY TABLE TO YUG_MSP;
  GRANT DROP ROLLBACK SEGMENT TO YUG_MSP;
  GRANT DEBUG CONNECT SESSION TO YUG_MSP;
  GRANT SELECT ANY DICTIONARY TO YUG_MSP;
  GRANT DROP ANY OUTLINE TO YUG_MSP;
  GRANT CREATE INDEXTYPE TO YUG_MSP;
  GRANT DROP ANY OPERATOR TO YUG_MSP;
  GRANT CREATE ANY OPERATOR TO YUG_MSP;
  GRANT ALTER ANY TYPE TO YUG_MSP;
  GRANT DROP ANY MATERIALIZED VIEW TO YUG_MSP;
  GRANT ANALYZE ANY TO YUG_MSP;
  GRANT CREATE TRIGGER TO YUG_MSP;
  GRANT AUDIT ANY TO YUG_MSP;
  GRANT CREATE ANY CONTEXT TO YUG_MSP;
  GRANT ALTER ANY TRIGGER TO YUG_MSP;
  GRANT EXECUTE ANY PROCEDURE TO YUG_MSP;
  GRANT ALTER ANY PROCEDURE TO YUG_MSP;
  GRANT CREATE PROCEDURE TO YUG_MSP;
  GRANT CREATE DATABASE LINK TO YUG_MSP;
  GRANT CREATE VIEW TO YUG_MSP;
  GRANT DROP ANY INDEX TO YUG_MSP;
  GRANT CREATE ANY INDEX TO YUG_MSP;
  GRANT CREATE ANY CLUSTER TO YUG_MSP;
  GRANT UPDATE ANY TABLE TO YUG_MSP;
  GRANT EXECUTE ANY TYPE TO YUG_MSP;
  GRANT CREATE ANY TYPE TO YUG_MSP;
  GRANT CREATE MATERIALIZED VIEW TO YUG_MSP;
  GRANT DROP ANY ROLE TO YUG_MSP;
  GRANT DROP ANY SEQUENCE TO YUG_MSP;
  GRANT DROP ANY VIEW TO YUG_MSP;
  GRANT DROP ANY CLUSTER TO YUG_MSP;
  GRANT DROP PUBLIC DATABASE LINK TO YUG_MSP;
  GRANT CREATE PUBLIC DATABASE LINK TO YUG_MSP;
  GRANT CREATE ANY SEQUENCE TO YUG_MSP;
  GRANT CREATE ANY TABLE TO YUG_MSP;
  GRANT BECOME USER TO YUG_MSP;
  GRANT UNLIMITED TABLESPACE TO YUG_MSP;
  GRANT DROP TABLESPACE TO YUG_MSP;
  GRANT ALTER SESSION TO YUG_MSP;
  GRANT CREATE ANY INDEXTYPE TO YUG_MSP;
  GRANT CREATE ANY LIBRARY TO YUG_MSP;
  GRANT CREATE TYPE TO YUG_MSP;
  GRANT CREATE PROFILE TO YUG_MSP;
  GRANT CREATE SEQUENCE TO YUG_MSP;
  GRANT DROP ANY DIMENSION TO YUG_MSP;
  GRANT GLOBAL QUERY REWRITE TO YUG_MSP;
  GRANT CREATE OPERATOR TO YUG_MSP;
  GRANT DROP ANY LIBRARY TO YUG_MSP;
  GRANT DROP ANY TYPE TO YUG_MSP;
  GRANT DROP ANY DIRECTORY TO YUG_MSP;
  GRANT DROP ANY TRIGGER TO YUG_MSP;
  GRANT CREATE ANY PROCEDURE TO YUG_MSP;
  GRANT COMMENT ANY TABLE TO YUG_MSP;
  GRANT ALTER ANY TABLE TO YUG_MSP;
  GRANT CREATE TABLE TO YUG_MSP;
  GRANT DROP USER TO YUG_MSP;
  GRANT CREATE USER TO YUG_MSP;
  GRANT CREATE TABLESPACE TO YUG_MSP;
  GRANT RESUMABLE TO YUG_MSP;
  GRANT ADMINISTER DATABASE TRIGGER TO YUG_MSP;
  GRANT DROP ANY INDEXTYPE TO YUG_MSP;
  GRANT CREATE ANY DIRECTORY TO YUG_MSP;
  GRANT DROP PROFILE TO YUG_MSP;
  GRANT DROP ANY PROCEDURE TO YUG_MSP;
  GRANT CREATE PUBLIC SYNONYM TO YUG_MSP;
  GRANT DROP ANY SYNONYM TO YUG_MSP;
  GRANT CREATE SYNONYM TO YUG_MSP;
  GRANT SELECT ANY TABLE TO YUG_MSP;
  GRANT CREATE ROLLBACK SEGMENT TO YUG_MSP;
  GRANT CREATE SESSION TO YUG_MSP;
  -- 3 Tablespace Quotas for YUG_MSP 
  ALTER USER YUG_MSP QUOTA UNLIMITED ON MSP_DATATS;
  ALTER USER YUG_MSP QUOTA UNLIMITED ON MSP_INDXTS;
