--demo data entity

--drop table "YUG_MSP"."FACILITYDEMO" cascade constraints;
--drop table "YUG_MSP"."AL_FACILITYDEMO" cascade constraints;

CREATE TABLE "YUG_MSP"."FACILITYDEMO" 
   (	"ID_PK" VARCHAR2(50 BYTE), 
	"VERSION" NUMBER NOT NULL ENABLE, 
	"CREATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"DELETED_TS" TIMESTAMP (6), 
	"UPDATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"UPDATED_BY_TXN_ID" VARCHAR2(100 BYTE), 
	"FACILITY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(50 BYTE), 
	 CONSTRAINT "FACILITYDEMO_PK" PRIMARY KEY ("ID_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_DATATS"  ENABLE
   )  TABLESPACE "MDM_DATATS" ;
   
   
   CREATE TABLE "YUG_MSP"."AL_FACILITYDEMO" 
   ("AUDITLOG_ID_PK" VARCHAR2(50 BYTE), 
	"AUDITLOG_CREATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"AUDITLOG_ACTION_CODE" CHAR(1 BYTE) NOT NULL ENABLE,    
   "ID_PK" VARCHAR2(50 BYTE), 
	"VERSION" NUMBER NOT NULL ENABLE, 
	"CREATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"DELETED_TS" TIMESTAMP (6), 
	"UPDATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"UPDATED_BY_TXN_ID" VARCHAR2(100 BYTE), 
	"FACILITY_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(50 BYTE), 
	 CONSTRAINT "AL_FACILITYDEMO_PK" PRIMARY KEY ("AUDITLOG_ID_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_DATATS"  ENABLE
   )  TABLESPACE "MDM_DATATS" ;

 COMMENT ON TABLE "YUG_MSP"."FACILITYDEMO"  IS 'Facility demo.';

  
  CREATE OR REPLACE TRIGGER "YUG_MSP"."I_FACILITYDEMO" AFTER INSERT ON YUG_MSP.FACILITYDEMO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN INSERT INTO AL_FACILITYDEMO ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, FACILITY_NAME, LOCATION ) VALUES( (select sys_guid() from dual), CURRENT_TIMESTAMP, 'I', :NEW.ID_PK, :NEW.VERSION, :NEW.CREATED_TS, :NEW.DELETED_TS, :NEW.UPDATED_TS, :NEW.UPDATED_BY_USER, :NEW.UPDATED_BY_TXN_ID, :NEW.FACILITY_NAME, :NEW.LOCATION); END;

/
ALTER TRIGGER "YUG_MSP"."I_FACILITYDEMO" ENABLE;

  CREATE OR REPLACE TRIGGER "YUG_MSP"."U_FACILITYDEMO" AFTER UPDATE ON YUG_MSP.FACILITYDEMO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN INSERT INTO AL_FACILITYDEMO ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, FACILITY_NAME, LOCATION ) VALUES( (select sys_guid() from dual), CURRENT_TIMESTAMP, 'U', :NEW.ID_PK, :NEW.VERSION, :NEW.CREATED_TS, :NEW.DELETED_TS, :NEW.UPDATED_TS, :NEW.UPDATED_BY_USER, :NEW.UPDATED_BY_TXN_ID, :NEW.FACILITY_NAME, :NEW.LOCATION); END;

/
ALTER TRIGGER "YUG_MSP"."U_FACILITYDEMO" ENABLE;

  CREATE OR REPLACE TRIGGER "YUG_MSP"."D_FACILITYDEMO" AFTER DELETE ON YUG_MSP.FACILITYDEMO REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN INSERT INTO AL_FACILITYDEMO ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, FACILITY_NAME, LOCATION ) VALUES( (select sys_guid() from dual), CURRENT_TIMESTAMP, 'D', :OLD.ID_PK, :OLD.VERSION, :OLD.CREATED_TS, :OLD.DELETED_TS, :OLD.UPDATED_TS, :OLD.UPDATED_BY_USER, :OLD.UPDATED_BY_TXN_ID, :OLD.FACILITY_NAME, :OLD.LOCATION); END;

/
ALTER TRIGGER "YUG_MSP"."D_FACILITYDEMO" ENABLE;


-- Demo Reference Entity---
--drop table "YUG_MSP"."REF_COLOR" cascade constraints;
--drop table "YUG_MSP"."AL_REF_COLOR" cascade constraints;


  CREATE TABLE "YUG_MSP"."REF_COLOR" 
   (	"ID_PK" VARCHAR2(50 BYTE), 
	"VERSION" NUMBER NOT NULL ENABLE, 
	"CREATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"DELETED_TS" TIMESTAMP (6), 
	"UPDATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"UPDATED_BY_TXN_ID" VARCHAR2(100 BYTE), 
	"CONFIG_LANGUAGE_CODE_KEY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"KEY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	 CONSTRAINT "REF_COLOR_PK" PRIMARY KEY ("ID_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_INDXTS"  ENABLE, 
	 CONSTRAINT "REF_COLOR_UNIQUEKEY" UNIQUE ("CONFIG_LANGUAGE_CODE_KEY", "KEY")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_INDXTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_DATATS" ;
  
  CREATE TABLE "YUG_MSP"."AL_REF_COLOR" 
   ("AUDITLOG_ID_PK" VARCHAR2(50 BYTE), 
	"AUDITLOG_CREATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"AUDITLOG_ACTION_CODE" CHAR(1 BYTE) NOT NULL ENABLE,  
    "ID_PK" VARCHAR2(50 BYTE), 
	"VERSION" NUMBER NOT NULL ENABLE, 
	"CREATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"DELETED_TS" TIMESTAMP (6), 
	"UPDATED_TS" TIMESTAMP (6) NOT NULL ENABLE, 
	"UPDATED_BY_USER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"UPDATED_BY_TXN_ID" VARCHAR2(100 BYTE), 
	"CONFIG_LANGUAGE_CODE_KEY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"KEY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(50 BYTE), 
	 CONSTRAINT "AL_REF_COLOR_PK" PRIMARY KEY ("ID_PK")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_INDXTS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDM_DATATS" ;
  
   CREATE OR REPLACE TRIGGER "YUG_MSP"."I_REF_COLOR" AFTER INSERT ON YUG_MSP.REF_COLOR REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN INSERT INTO AL_REF_COLOR ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, CONFIG_LANGUAGE_CODE_KEY, KEY, VALUE, DESCRIPTION ) VALUES( (select sys_guid() from dual), CURRENT_TIMESTAMP, 'I', :NEW.ID_PK, :NEW.VERSION, :NEW.CREATED_TS, :NEW.DELETED_TS, :NEW.UPDATED_TS, :NEW.UPDATED_BY_USER, :NEW.UPDATED_BY_TXN_ID, :NEW.CONFIG_LANGUAGE_CODE_KEY, :NEW.KEY, :NEW.VALUE, :NEW.DESCRIPTION); END;

/
ALTER TRIGGER "YUG_MSP"."I_REF_COLOR" ENABLE;

  CREATE OR REPLACE TRIGGER "YUG_MSP"."U_REF_COLOR" AFTER UPDATE ON YUG_MSP.REF_COLOR REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN INSERT INTO AL_REF_COLOR ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, CONFIG_LANGUAGE_CODE_KEY, KEY, VALUE, DESCRIPTION ) VALUES( (select sys_guid() from dual), CURRENT_TIMESTAMP, 'U', :NEW.ID_PK, :NEW.VERSION, :NEW.CREATED_TS, :NEW.DELETED_TS, :NEW.UPDATED_TS, :NEW.UPDATED_BY_USER, :NEW.UPDATED_BY_TXN_ID, :NEW.CONFIG_LANGUAGE_CODE_KEY, :NEW.KEY, :NEW.VALUE, :NEW.DESCRIPTION); END;

/
ALTER TRIGGER "YUG_MSP"."U_REF_COLOR" ENABLE;

  CREATE OR REPLACE TRIGGER "YUG_MSP"."D_REF_COLOR" AFTER DELETE ON YUG_MSP.REF_COLOR REFERENCING NEW AS NEW OLD AS OLD FOR EACH ROW
BEGIN INSERT INTO AL_REF_COLOR ( AUDITLOG_ID_PK, AUDITLOG_CREATED_TS, AUDITLOG_ACTION_CODE ,ID_PK, VERSION, CREATED_TS, DELETED_TS, UPDATED_TS, UPDATED_BY_USER, UPDATED_BY_TXN_ID, CONFIG_LANGUAGE_CODE_KEY, KEY, VALUE, DESCRIPTION ) VALUES( (select sys_guid() from dual), CURRENT_TIMESTAMP, 'D', :OLD.ID_PK, :OLD.VERSION, :OLD.CREATED_TS, :OLD.DELETED_TS, :OLD.UPDATED_TS, :OLD.UPDATED_BY_USER, :OLD.UPDATED_BY_TXN_ID, :OLD.CONFIG_LANGUAGE_CODE_KEY, :OLD.KEY, :OLD.VALUE, :OLD.DESCRIPTION); END;

/
ALTER TRIGGER "YUG_MSP"."D_REF_COLOR" ENABLE;

